name: Build, Push and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ci-cd-${{ github.ref }}

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASENAME: ${{ github.repository }}

jobs:
  ci:
    name: "Build and Deploy"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    environment:
      name: ci-cd-web-dev

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Autenticação no GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Construção e publicação da imagem de contêiner
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          target: web-runtime
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/web:development
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/web:cache-development
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/web:cache-development,mode=max

  cd:
    name: "Deploy"
    
    runs-on: dev-deploy

    permissions:
      contents: read

    needs: [ ci ]

    environment:
      name: development
      url: ${{ vars.DEPLOY_URL }}

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v6

      - name: Implantação da aplicação no Kubernetes
        shell: bash
        working-directory: ./.deploy/development/
        run: bash ./deploy.sh
